### ISSUE TITLE
Incorrect whitelist property package path

### ISSUE THREAD

**Issue by tzolov** [spring-cloud-stream-app-starters/header-enricher#2]
The `HeaderEnricherProcessorProperties` properties are not visible for auto-completion because of incorrect package path in the [configuration-metadata-whitelist.properties ](https://github.com/spring-cloud-stream-app-starters/header-enricher/blob/master/spring-cloud-starter-stream-processor-header-enricher/src/main/resources/META-INF/spring-configuration-metadata-whitelist.properties#L1).

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-cloud-stream-app-starters/header-enricher/commit/467cbb2f4c03d2de999e00a1e47fb1ce2f63b907
