### ISSUE TITLE
Properties whitelist not working

### ISSUE THREAD

**Issue by dturanski** [spring-cloud-stream-app-starters/header-enricher#4]
Probably because https://github.com/spring-cloud-stream-app-starters/header-enricher/blob/master/spring-cloud-starter-stream-processor-header-enricher/src/main/java/org/springframework/cloud/stream/app/header/enricher/processor/HeaderEnricherProcessorProperties.java#L32 needs to be `header-enricher`

If you use `--headers` , you get an NPE.  Currently must be `--header.enricher.headers`.

**Comment by artembilan** [comment]
Looks like #2 has fixed that already.
Plus NPE has been fixed with the  https://github.com/spring-cloud-stream-app-starters/header-enricher/commit/fa45b72038d758216147d43dd61a5e41ea575294 As well.
