### ISSUE TITLE
The header.enricher.headers config prop doesn't work in Spring Cloud Dataflow

### ISSUE THREAD

**Issue by jhines2k7** [spring-cloud-stream-app-starters/header-enricher#6]
I'm unable to use the header.enricher.headers config property to add headers to a message in Spring Cloud Dataflow. Here's a link to a [Stackoverflow question](https://stackoverflow.com/questions/44661301/how-do-i-add-a-header-to-a-message-using-the-header-enricher-spring-cloud-stream) that describes the issue I'm seeing:

https://stackoverflow.com/questions/44661301/how-do-i-add-a-header-to-a-message-using-the-header-enricher-spring-cloud-stream

**Comment by artembilan** [comment]
Has been fixed via https://github.com/spring-cloud/spring-cloud-dataflow/pull/1540 and presented in the latest Spring Cloud Data Flow 1.2.3: https://spring.io/blog/2017/07/26/spring-cloud-data-flow-1-2-3-released
